name: keywarden
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  hive_flutter: ^1.1.0
  any_link_preview: ^3.0.1
  cached_network_image: ^3.2.3
  go_router: ^10.1.2
  provider: ^6.0.5
  path_provider: ^2.0.10
  hive: ^2.2.3
  share_plus: ^4.5.3
  file_picker: ^5.5.0
  pay: ^1.1.2
  cross_file: ^0.3.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true